project_id = "yztwwehxppldoecwhomg"

[functions.send-email]
verify_jwt = false

[functions.fetch-car-info]
verify_jwt = false

[functions.fortnox-oauth]
verify_jwt = false

[functions.fortnox-sync-purchase]
verify_jwt = true

[functions.fortnox-makulering-verifikat]
verify_jwt = true

[functions.fortnox-moms-inkop]
verify_jwt = true

[functions.fortnox-momsi-inkop]
verify_jwt = true

[functions.fortnox-vmb-inkop]
verify_jwt = true

[functions.fortnox-vmbi-inkop]
verify_jwt = true