project_id = "yztwwehxppldoecwhomg"

[functions.send-email]
verify_jwt = false

[functions.fetch-car-info]
verify_jwt = false

[functions.fortnox-oauth]
verify_jwt = true

[functions.fortnox-sync]
verify_jwt = true